// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Currencies is an enum which represents the allowed currencies for the API
type Currencies int32

const (
	Currencies_EUR Currencies = 0
	Currencies_USD Currencies = 1
	Currencies_JPY Currencies = 2
	Currencies_BGN Currencies = 3
	Currencies_CZK Currencies = 4
	Currencies_DKK Currencies = 5
	Currencies_GBP Currencies = 6
	Currencies_HUF Currencies = 7
	Currencies_PLN Currencies = 8
	Currencies_RON Currencies = 9
	Currencies_SEK Currencies = 10
	Currencies_CHF Currencies = 11
	Currencies_ISK Currencies = 12
	Currencies_NOK Currencies = 13
	Currencies_HRK Currencies = 14
	Currencies_RUB Currencies = 15
	Currencies_TRY Currencies = 16
	Currencies_AUD Currencies = 17
	Currencies_BRL Currencies = 18
	Currencies_CAD Currencies = 19
	Currencies_CNY Currencies = 20
	Currencies_HKD Currencies = 21
	Currencies_IDR Currencies = 22
	Currencies_ILS Currencies = 23
	Currencies_INR Currencies = 24
	Currencies_KRW Currencies = 25
	Currencies_MXN Currencies = 26
	Currencies_MYR Currencies = 27
	Currencies_NZD Currencies = 28
	Currencies_PHP Currencies = 29
	Currencies_SGD Currencies = 30
	Currencies_THB Currencies = 31
	Currencies_ZAR Currencies = 32
)

var Currencies_name = map[int32]string{
	0:  "EUR",
	1:  "USD",
	2:  "JPY",
	3:  "BGN",
	4:  "CZK",
	5:  "DKK",
	6:  "GBP",
	7:  "HUF",
	8:  "PLN",
	9:  "RON",
	10: "SEK",
	11: "CHF",
	12: "ISK",
	13: "NOK",
	14: "HRK",
	15: "RUB",
	16: "TRY",
	17: "AUD",
	18: "BRL",
	19: "CAD",
	20: "CNY",
	21: "HKD",
	22: "IDR",
	23: "ILS",
	24: "INR",
	25: "KRW",
	26: "MXN",
	27: "MYR",
	28: "NZD",
	29: "PHP",
	30: "SGD",
	31: "THB",
	32: "ZAR",
}

var Currencies_value = map[string]int32{
	"EUR": 0,
	"USD": 1,
	"JPY": 2,
	"BGN": 3,
	"CZK": 4,
	"DKK": 5,
	"GBP": 6,
	"HUF": 7,
	"PLN": 8,
	"RON": 9,
	"SEK": 10,
	"CHF": 11,
	"ISK": 12,
	"NOK": 13,
	"HRK": 14,
	"RUB": 15,
	"TRY": 16,
	"AUD": 17,
	"BRL": 18,
	"CAD": 19,
	"CNY": 20,
	"HKD": 21,
	"IDR": 22,
	"ILS": 23,
	"INR": 24,
	"KRW": 25,
	"MXN": 26,
	"MYR": 27,
	"NZD": 28,
	"PHP": 29,
	"SGD": 30,
	"THB": 31,
	"ZAR": 32,
}

func (x Currencies) String() string {
	return proto.EnumName(Currencies_name, int32(x))
}

func (Currencies) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{0}
}

// RateRequest defines the request for a GetRate call
type RateRequest struct {
	// Base is the base currency code for the rate
	Base Currencies `protobuf:"varint,1,opt,name=Base,proto3,enum=protos.Currencies" json:"Base,omitempty"`
	// Destination is the destination currency code for the rate
	Destination          Currencies `protobuf:"varint,2,opt,name=Destination,proto3,enum=protos.Currencies" json:"Destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RateRequest) Reset()         { *m = RateRequest{} }
func (m *RateRequest) String() string { return proto.CompactTextString(m) }
func (*RateRequest) ProtoMessage()    {}
func (*RateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{0}
}

func (m *RateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateRequest.Unmarshal(m, b)
}
func (m *RateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateRequest.Marshal(b, m, deterministic)
}
func (m *RateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateRequest.Merge(m, src)
}
func (m *RateRequest) XXX_Size() int {
	return xxx_messageInfo_RateRequest.Size(m)
}
func (m *RateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RateRequest proto.InternalMessageInfo

func (m *RateRequest) GetBase() Currencies {
	if m != nil {
		return m.Base
	}
	return Currencies_EUR
}

func (m *RateRequest) GetDestination() Currencies {
	if m != nil {
		return m.Destination
	}
	return Currencies_EUR
}

// RateResponse is the response from a GetRate call
type RateResponse struct {
	// Rate number and can be used to convert between the two currencies specified in the request.
	Rate                 float64  `protobuf:"fixed64,1,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateResponse) Reset()         { *m = RateResponse{} }
func (m *RateResponse) String() string { return proto.CompactTextString(m) }
func (*RateResponse) ProtoMessage()    {}
func (*RateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3dc60ed002193ea, []int{1}
}

func (m *RateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateResponse.Unmarshal(m, b)
}
func (m *RateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateResponse.Marshal(b, m, deterministic)
}
func (m *RateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateResponse.Merge(m, src)
}
func (m *RateResponse) XXX_Size() int {
	return xxx_messageInfo_RateResponse.Size(m)
}
func (m *RateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RateResponse proto.InternalMessageInfo

func (m *RateResponse) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func init() {
	proto.RegisterEnum("protos.Currencies", Currencies_name, Currencies_value)
	proto.RegisterType((*RateRequest)(nil), "protos.RateRequest")
	proto.RegisterType((*RateResponse)(nil), "protos.RateResponse")
}

func init() {
	proto.RegisterFile("currency.proto", fileDescriptor_d3dc60ed002193ea)
}

var fileDescriptor_d3dc60ed002193ea = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd2, 0xcf, 0xae, 0xd2, 0x40,
	0x14, 0x06, 0x70, 0xcb, 0xc5, 0x0b, 0x0e, 0x57, 0xfc, 0x1c, 0x50, 0x11, 0xff, 0x11, 0x16, 0xc6,
	0xb8, 0xc0, 0x04, 0x79, 0x00, 0x29, 0x03, 0xad, 0x0e, 0x96, 0x66, 0x6a, 0xa3, 0xed, 0x0e, 0xc9,
	0x2c, 0x88, 0x49, 0x8b, 0x4c, 0x59, 0xf0, 0x60, 0xbe, 0x9f, 0x39, 0xa7, 0x1a, 0x71, 0x71, 0x57,
	0xfd, 0xb5, 0x73, 0xbe, 0x99, 0x93, 0x39, 0x15, 0xdd, 0xdd, 0xe9, 0x78, 0xb4, 0xc5, 0xee, 0x3c,
	0x39, 0x1c, 0xcb, 0xaa, 0x94, 0xd7, 0xfc, 0x70, 0xe3, 0x1f, 0xa2, 0x63, 0xb6, 0x95, 0x35, 0xf6,
	0xe7, 0xc9, 0xba, 0x4a, 0xbe, 0x16, 0x4d, 0x7f, 0xeb, 0xec, 0xc0, 0x1b, 0x79, 0x6f, 0xba, 0x53,
	0x59, 0x17, 0xbb, 0xc9, 0xa2, 0x0e, 0xef, 0xad, 0x33, 0xbc, 0x2e, 0x67, 0xa2, 0xa3, 0xac, 0xab,
	0xf6, 0xc5, 0xb6, 0xda, 0x97, 0xc5, 0xa0, 0x71, 0x6b, 0xf9, 0x65, 0xd9, 0x78, 0x2c, 0x6e, 0xea,
	0xc3, 0xdc, 0xa1, 0x2c, 0x9c, 0x95, 0x52, 0x34, 0xe9, 0x9d, 0x4f, 0xf3, 0x0c, 0xfb, 0xed, 0xaf,
	0x86, 0x10, 0xff, 0xf2, 0xb2, 0x25, 0xae, 0x96, 0xa9, 0xc1, 0x1d, 0x42, 0x9a, 0x28, 0x78, 0x84,
	0x4f, 0x71, 0x86, 0x06, 0xc1, 0x0f, 0x22, 0x5c, 0x11, 0x16, 0xb9, 0x46, 0x93, 0xa0, 0xb4, 0xc6,
	0x5d, 0x42, 0xe0, 0xc7, 0xb8, 0x26, 0x84, 0xe9, 0x0a, 0x2d, 0x42, 0xbc, 0x8e, 0xd0, 0x26, 0x98,
	0x4d, 0x84, 0x7b, 0x84, 0x64, 0xa9, 0x21, 0x38, 0x1e, 0xae, 0xd0, 0x21, 0x7c, 0x4c, 0x34, 0x6e,
	0x08, 0xd1, 0x46, 0xe3, 0x3e, 0xc7, 0x8d, 0x46, 0x97, 0x53, 0xa9, 0x8f, 0x07, 0x84, 0x2f, 0x26,
	0x03, 0x08, 0xf3, 0x54, 0xe1, 0x21, 0xb7, 0x61, 0xd6, 0x90, 0xbc, 0xcf, 0x5c, 0xa1, 0xc7, 0x88,
	0x32, 0xf4, 0x39, 0xae, 0x15, 0x1e, 0xf1, 0xce, 0xca, 0xe0, 0x31, 0x63, 0x9d, 0xe0, 0x09, 0x23,
	0x32, 0x18, 0x10, 0xb4, 0xf9, 0x8a, 0xa7, 0x84, 0xcf, 0xdf, 0x22, 0x0c, 0x19, 0x99, 0xc1, 0x33,
	0x6e, 0x23, 0x57, 0x78, 0xce, 0xcd, 0x87, 0x31, 0x5e, 0x70, 0xcf, 0x81, 0xc2, 0x4b, 0x6e, 0x23,
	0xf4, 0xf1, 0x8a, 0x90, 0xcf, 0x0d, 0x46, 0xd3, 0x0f, 0xa2, 0xfd, 0xe7, 0xda, 0xce, 0x72, 0x26,
	0x5a, 0x81, 0xad, 0xe8, 0x3a, 0x65, 0xef, 0xef, 0x4c, 0x2e, 0xa6, 0x3c, 0xec, 0xff, 0xff, 0xb1,
	0x9e, 0x86, 0x2f, 0xf2, 0xf6, 0xe4, 0x5d, 0xbd, 0xf0, 0xbd, 0xfe, 0x3d, 0xde, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x82, 0xfc, 0x35, 0xd6, 0x37, 0x02, 0x00, 0x00,
}
